name: fcs_directus
description: A library for http request with an Directus server.
version: 0.0.5
repository: https://github.com/fracosfr/fcs_directus

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  http: ^0.13.5
  reflectable: ^4.0.4
