name: fcs_directus
description: A library for http request with an Directus server.
version: 0.0.52
repository: https://github.com/fracosfr/fcs_directus

environment:
  sdk: ^3.5.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0

dependencies:
  http: ^1.1.0
  meta: ^1.9.1
  mime: ^2.0.0
  path: ^1.9.0
  http_parser: ^4.0.2
  web_socket_channel: ^3.0.1
