name: fcs_directus
description: A library for http request with an Directus server.
version: 0.0.52
repository: https://github.com/fracosfr/fcs_directus

environment:
  sdk: '>=2.18.6 <3.0.0'
  #sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

dependencies:
  http: ^1.1.0
  meta: ^1.9.1
  mime: ^1.0.5
  path: ^1.9.0
  http_parser: ^4.0.2
